services:
  playit:
    image: ghcr.io/playit-cloud/playit-agent:latest
    container_name: playit
    restart: unless-stopped
    network_mode: "service:minecraft"
    env_file:
      - .env
    volumes:
      - playit-data:/etc/playit
    depends_on:
      - minecraft

  minecraft:
    build:
      context: .
    container_name: minecraft-server
    ports:
     - "25565:25565"
     - "19132:19132/udp" 
    restart: unless-stopped
    volumes:
      - minecraft-data:/server
    env_file:
      - .env

volumes:
  minecraft-data:
  playit-data:

