services:
  minecraft:
    build:
      context: .
    container_name: minecraft-server
    ports:
      - "25565:25565"
    restart: unless-stopped
    volumes:
      - minecraft-data:/server
    env_file:
      - .env
volumes:
  minecraft-data: {}
 

